### PR TITLE
added mergesort.py

### PR DESCRIPTION
**Pull request by heyyviv**

### CODE REVIEW

**Comment by codePerfectPlus** [comment]
Thanks for making PR @heyyviv 

Note - please keep in mind that HacktoberFest isn’t yet counting pull requests. **Only pull requests submitted October 1st - 31st will count toward winning a t-shirt or the option to plant a tree.**

**Comment by heyyviv** [comment]
I didn't knew that

**Comment by heyyviv** [comment]
What should I do

**Comment by codePerfectPlus** [comment]
Check previous program, documentation and bug fixes and create a new pull request between 1 October to 31 October.

Happy coding,

**Pull request merged**
